package com.example.CVRUK_backend.authentication.enums;

public enum enum_permission {
    
    // ===== PUBLIC ACCESS =====
    PUBLIC_VIEW_CONTENT,        // anyone can view public data

    // ===== STUDENT =====
    STUDENT_VIEW_PROFILE,
    STUDENT_UPDATE_PROFILE,
    STUDENT_VIEW_COURSES,
    STUDENT_VIEW_RESULTS,
    STUDENT_SUBMIT_FEEDBACK,
    STUDENT_VIEW_CONTENT,
    STUDENT_REGISTER_EVENT,

    // ===== FACULTY =====
    FACULTY_VIEW_PROFILE,
    FACULTY_UPDATE_PROFILE,
    FACULTY_MANAGE_RESULTS,
    FACULTY_MANAGE_ATTENDANCE,
    FACULTY_MANAGE_EVENTS,
    FACULTY_UPLOAD_MATERIAL,

    // ===== ADMIN =====
    ADMIN_VIEW_ALL,
    ADMIN_MANAGE_USERS,
    ADMIN_MANAGE_ROLES,
    ADMIN_MANAGE_EVENTS,
    ADMIN_MANAGE_NEWS,
    ADMIN_MANAGE_SPORTS,
    ADMIN_MANAGE_PLACEMENTS,
    ADMIN_MANAGE_COURSES,
    ADMIN_DELETE_ANY

    
}